# configuration file for the shared solar message parser 

classifers:
  - name: consumer-message-numeric
    classifer: ^[0-9]
    parser: ssgateway.message.parsers.parse_consumer

  - name: consummer-message-alphabetical
    classifer: ^[A-Za-z]
    parser: ssgateway.message.parsers.parse_consumer
    
  - name: meter-message-compressed
    classifer: ^\(l.*\)$
    parser: ssgateway.message.parsers.parse_meter_compressed

  - name: meter-message-pcu
    classifer: ^\(pcu*
    parser: ssgateway.message.parsers.parse_meter_pcu

  - name: meter-message-uncompressed
    classifer: ^\(.*\)$
    parser: ssgateway.message.parsers.parse_meter

routes:
  - name: ssgateway.message.routes.check_circuit_balance
    commands: [bal, solde, 2]

  - name: ssgateway.message.routes.add_credit
    commands: [add, recharge, 9]

  - name: ssgateway.message.routes.turn_on
    commands: [on, 1]

  - name: ssgateway.message.routes.turn_off
    commands: [off, 0]

  - name: ssgateway.message.routes.set_primary_phone
    commands: [prim, tel, 4]

  - name: ssgateway.message.routes.get_user_history
    commands: [use, 3]

  - name: ssgateway.message.routes.meter.alert_meter_online
    commands: [online]